# Generated by Django 5.1.6 on 2025-02-10 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('personality', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalityresult',
            name='test_taker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personality', to='home.testtaker'),
        ),
    ]
