# Generated by Django 5.1.6 on 2025-02-12 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('personality', '0002_alter_personalityresult_test_taker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalityresult',
            name='test_taker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.testtaker'),
        ),
    ]
